export const OUTER_BOX_OFFSET = 10;

export const SELECTION_BOX_CONTROL_POINT_SIZE = 10;
export const SELECTION_BOX_OFFSET = SELECTION_BOX_CONTROL_POINT_SIZE / 2;

export const SELECTION_COLOR = "#34b4eb";
